import React, { useState } from 'react';
import type { DesignResult } from '../types';

interface SequenceViewerProps {
  result: DesignResult;
  targetName: string;
}

export const SequenceViewer: React.FC<SequenceViewerProps> = ({ result, targetName }) => {
  const [copied, setCopied] = useState(false);
  const [hoveredResidue, setHoveredResidue] = useState<{ res: string; idx: number; conf: number } | null>(null);

  const getConfidenceColor = (conf: number) => {
    if (conf >= 0.70) return '#10b981'; // Emerald
    if (conf >= 0.40) return '#f59e0b'; // Amber
    return '#f43f5e'; // Rose
  };

  const handleCopyFASTA = () => {
    const fasta = `>ProteinSolver_Design_${targetName}_${result.strategy}_seed${result.seed || 'none'}\n${result.sequence}`;
    navigator.clipboard.writeText(fasta);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadFASTA = () => {
    const fasta = `>ProteinSolver_Design_${targetName}_${result.strategy}_seed${result.seed || 'none'}\n${result.sequence}`;
    const blob = new Blob([fasta], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `proteinsolver_design_${targetName}.fasta`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="glass-card" style={{ padding: '24px' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>
        <div>
          <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--text-primary)' }}>Generated Amino Acid Sequence</h2>
          <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
            Inverse folding sequence generated by ProteinSolver GNN
          </p>
        </div>
        <div style={{ display: 'flex', gap: '8px' }}>
          <button onClick={handleCopyFASTA} className="btn btn-secondary" style={{ fontSize: '0.82rem', padding: '6px 12px' }}>
            {copied ? '✅ Copied!' : '📋 Copy FASTA'}
          </button>
          <button onClick={handleDownloadFASTA} className="btn btn-secondary" style={{ fontSize: '0.82rem', padding: '6px 12px' }}>
            💾 Download
          </button>
        </div>
      </div>

      {/* Metrics Row */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px', marginBottom: '20px' }}>
        <div style={{ background: 'rgba(255,255,255,0.03)', padding: '12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)', display: 'block' }}>Length</span>
          <span style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--text-primary)' }}>{result.length} AA</span>
        </div>
        <div style={{ background: 'rgba(255,255,255,0.03)', padding: '12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)', display: 'block' }}>Inference Runtime</span>
          <span style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--accent-cyan)' }}>{result.runtime_seconds}s</span>
        </div>
        <div style={{ background: 'rgba(255,255,255,0.03)', padding: '12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)', display: 'block' }}>Mean Confidence</span>
          <span style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--accent-emerald)' }}>{(result.mean_confidence * 100).toFixed(1)}%</span>
        </div>
        <div style={{ background: 'rgba(255,255,255,0.03)', padding: '12px', borderRadius: '10px', border: '1px solid var(--border-subtle)' }}>
          <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)', display: 'block' }}>Strategy</span>
          <span style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--text-primary)', textTransform: 'uppercase' }}>{result.strategy}</span>
        </div>
      </div>

      {/* Interactive Residue Tiles */}
      <div style={{ marginBottom: '14px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}>
          <span style={{ fontSize: '0.75rem', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase' }}>
            Per-Residue Model Confidence:
          </span>
          {hoveredResidue && (
            <span style={{ fontSize: '0.8rem', color: 'var(--accent-cyan)', fontFamily: 'var(--font-mono)' }}>
              Position {hoveredResidue.idx + 1}: <strong>{hoveredResidue.res}</strong> ({(hoveredResidue.conf * 100).toFixed(1)}% confidence)
            </span>
          )}
        </div>

        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px', background: 'rgba(0,0,0,0.3)', padding: '16px', borderRadius: '12px', border: '1px solid var(--border-subtle)', fontFamily: 'var(--font-mono)' }}>
          {result.sequence.split('').map((res, i) => {
            const conf = result.confidences[i] || 0.5;
            const color = getConfidenceColor(conf);
            return (
              <div
                key={i}
                onMouseEnter={() => setHoveredResidue({ res, idx: i, conf })}
                onMouseLeave={() => setHoveredResidue(null)}
                style={{
                  width: '28px',
                  height: '32px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  borderRadius: '4px',
                  background: 'rgba(255,255,255,0.05)',
                  borderBottom: `3px solid ${color}`,
                  color: 'var(--text-primary)',
                  fontSize: '0.9rem',
                  fontWeight: 600,
                  cursor: 'pointer',
                  transition: 'transform 0.1s ease',
                }}
              >
                {res}
              </div>
            );
          })}
        </div>
      </div>

      {/* Legend */}
      <div style={{ display: 'flex', gap: '16px', fontSize: '0.75rem', color: 'var(--text-muted)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          <span style={{ width: '10px', height: '10px', borderRadius: '2px', background: '#10b981' }} />
          <span>High Confidence (&ge; 70%)</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          <span style={{ width: '10px', height: '10px', borderRadius: '2px', background: '#f59e0b' }} />
          <span>Moderate (40–69%)</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          <span style={{ width: '10px', height: '10px', borderRadius: '2px', background: '#f43f5e' }} />
          <span>Low (&lt; 40%)</span>
        </div>
      </div>
    </div>
  );
};
